// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types.proto

package types

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/googleapis/google/api"
import _ "github.com/gogo/protobuf/gogoproto"
import types "github.com/gogo/protobuf/types"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "github.com/mwitkow/go-proto-validators"

import time "time"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Role int32

const (
	Role_GUEST  Role = 0
	Role_MEMBER Role = 1
	Role_ADMIN  Role = 2
)

var Role_name = map[int32]string{
	0: "GUEST",
	1: "MEMBER",
	2: "ADMIN",
}
var Role_value = map[string]int32{
	"GUEST":  0,
	"MEMBER": 1,
	"ADMIN":  2,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}
func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{0}
}

// models
type User struct {
	ID                   uint32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" topValue`
	Role                 Role            `protobuf:"varint,2,opt,name=role,proto3,enum=types.Role" json:"role,omitempty"`
	Name                 string          `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string          `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	AvatarUrl            string          `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	CreatedAt            *time.Time      `protobuf:"bytes,6,opt,name=created_at,json=createdAt,stdtime" json:"created_at,omitempty"`
	UpdatedAt            *time.Time      `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,stdtime" json:"updated_at,omitempty"`
	Projects             []*Project      `protobuf:"bytes,8,rep,name=projects" json:"projects,omitempty"`
	Organizations        []*Organization `protobuf:"bytes,9,rep,name=organizations" json:"organizations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_GUEST
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *User) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *User) GetCreatedAt() *time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *time.Time {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

func (m *User) GetOrganizations() []*Organization {
	if m != nil {
		return m.Organizations
	}
	return nil
}

type Object struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Etag                 string     `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	Size_                uint64     `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	CreatedAt            *time.Time `protobuf:"bytes,4,opt,name=created_at,json=createdAt,stdtime" json:"created_at,omitempty"`
	UpdatedAt            *time.Time `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,stdtime" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{1}
}
func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (dst *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(dst, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Object) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

func (m *Object) GetSize_() uint64 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *Object) GetCreatedAt() *time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Object) GetUpdatedAt() *time.Time {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type Project struct {
	ID                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string     `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	CreatedAt            *time.Time `protobuf:"bytes,4,opt,name=created_at,json=createdAt,stdtime" json:"created_at,omitempty"`
	Author               *User      `protobuf:"bytes,5,opt,name=author" json:"author,omitempty"`
	Private              bool       `protobuf:"varint,6,opt,name=private,proto3" json:"private,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{2}
}
func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (dst *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(dst, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Project) GetCreatedAt() *time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Project) GetAuthor() *User {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Project) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

type Dataset struct {
	ID                   uint32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string     `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Description          string     `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Preprocessing        string     `protobuf:"bytes,5,opt,name=preprocessing,proto3" json:"preprocessing,omitempty"`
	Instances            int32      `protobuf:"varint,6,opt,name=instances,proto3" json:"instances,omitempty"`
	Format               []string   `protobuf:"bytes,7,rep,name=format" json:"format,omitempty"`
	Labels               []string   `protobuf:"bytes,8,rep,name=labels" json:"labels,omitempty"`
	PublishAt            *time.Time `protobuf:"bytes,9,opt,name=publish_at,json=publishAt,stdtime" json:"publish_at,omitempty"`
	ModifyAt             *time.Time `protobuf:"bytes,10,opt,name=modify_at,json=modifyAt,stdtime" json:"modify_at,omitempty"`
	CreatedAt            *time.Time `protobuf:"bytes,11,opt,name=created_at,json=createdAt,stdtime" json:"created_at,omitempty"`
	Resources            []string   `protobuf:"bytes,12,rep,name=resources" json:"resources,omitempty"`
	Lisense              string     `protobuf:"bytes,13,opt,name=lisense,proto3" json:"lisense,omitempty"`
	Reference            []string   `protobuf:"bytes,14,rep,name=reference" json:"reference,omitempty"`
	Creators             []string   `protobuf:"bytes,15,rep,name=creators" json:"creators,omitempty"`
	Private              bool       `protobuf:"varint,16,opt,name=private,proto3" json:"private,omitempty"`
	Author               *User      `protobuf:"bytes,17,opt,name=author" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Dataset) Reset()         { *m = Dataset{} }
func (m *Dataset) String() string { return proto.CompactTextString(m) }
func (*Dataset) ProtoMessage()    {}
func (*Dataset) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{3}
}
func (m *Dataset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dataset.Unmarshal(m, b)
}
func (m *Dataset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dataset.Marshal(b, m, deterministic)
}
func (dst *Dataset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dataset.Merge(dst, src)
}
func (m *Dataset) XXX_Size() int {
	return xxx_messageInfo_Dataset.Size(m)
}
func (m *Dataset) XXX_DiscardUnknown() {
	xxx_messageInfo_Dataset.DiscardUnknown(m)
}

var xxx_messageInfo_Dataset proto.InternalMessageInfo

func (m *Dataset) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Dataset) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Dataset) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Dataset) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Dataset) GetPreprocessing() string {
	if m != nil {
		return m.Preprocessing
	}
	return ""
}

func (m *Dataset) GetInstances() int32 {
	if m != nil {
		return m.Instances
	}
	return 0
}

func (m *Dataset) GetFormat() []string {
	if m != nil {
		return m.Format
	}
	return nil
}

func (m *Dataset) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Dataset) GetPublishAt() *time.Time {
	if m != nil {
		return m.PublishAt
	}
	return nil
}

func (m *Dataset) GetModifyAt() *time.Time {
	if m != nil {
		return m.ModifyAt
	}
	return nil
}

func (m *Dataset) GetCreatedAt() *time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Dataset) GetResources() []string {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *Dataset) GetLisense() string {
	if m != nil {
		return m.Lisense
	}
	return ""
}

func (m *Dataset) GetReference() []string {
	if m != nil {
		return m.Reference
	}
	return nil
}

func (m *Dataset) GetCreators() []string {
	if m != nil {
		return m.Creators
	}
	return nil
}

func (m *Dataset) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

func (m *Dataset) GetAuthor() *User {
	if m != nil {
		return m.Author
	}
	return nil
}

type Organization struct {
	ID                   uint32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string     `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Description          string     `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	SiteUrl              string     `protobuf:"bytes,5,opt,name=site_url,json=siteUrl,proto3" json:"site_url,omitempty"`
	HomeUrl              string     `protobuf:"bytes,6,opt,name=home_url,json=homeUrl,proto3" json:"home_url,omitempty"`
	AvatarUrl            string     `protobuf:"bytes,7,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Owner                *User      `protobuf:"bytes,8,opt,name=owner" json:"owner,omitempty"`
	CreatedAt            *time.Time `protobuf:"bytes,9,opt,name=created_at,json=createdAt,stdtime" json:"created_at,omitempty"`
	UpdatedAt            *time.Time `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,stdtime" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Organization) Reset()         { *m = Organization{} }
func (m *Organization) String() string { return proto.CompactTextString(m) }
func (*Organization) ProtoMessage()    {}
func (*Organization) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{4}
}
func (m *Organization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Organization.Unmarshal(m, b)
}
func (m *Organization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Organization.Marshal(b, m, deterministic)
}
func (dst *Organization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Organization.Merge(dst, src)
}
func (m *Organization) XXX_Size() int {
	return xxx_messageInfo_Organization.Size(m)
}
func (m *Organization) XXX_DiscardUnknown() {
	xxx_messageInfo_Organization.DiscardUnknown(m)
}

var xxx_messageInfo_Organization proto.InternalMessageInfo

func (m *Organization) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Organization) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Organization) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Organization) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Organization) GetSiteUrl() string {
	if m != nil {
		return m.SiteUrl
	}
	return ""
}

func (m *Organization) GetHomeUrl() string {
	if m != nil {
		return m.HomeUrl
	}
	return ""
}

func (m *Organization) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *Organization) GetOwner() *User {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Organization) GetCreatedAt() *time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Organization) GetUpdatedAt() *time.Time {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

// Request/Response Types
type UsersReply struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersReply) Reset()         { *m = UsersReply{} }
func (m *UsersReply) String() string { return proto.CompactTextString(m) }
func (*UsersReply) ProtoMessage()    {}
func (*UsersReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{5}
}
func (m *UsersReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersReply.Unmarshal(m, b)
}
func (m *UsersReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersReply.Marshal(b, m, deterministic)
}
func (dst *UsersReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersReply.Merge(dst, src)
}
func (m *UsersReply) XXX_Size() int {
	return xxx_messageInfo_UsersReply.Size(m)
}
func (m *UsersReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersReply.DiscardUnknown(m)
}

var xxx_messageInfo_UsersReply proto.InternalMessageInfo

func (m *UsersReply) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type ProjectsReply struct {
	Projects             []*Project `protobuf:"bytes,1,rep,name=projects" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProjectsReply) Reset()         { *m = ProjectsReply{} }
func (m *ProjectsReply) String() string { return proto.CompactTextString(m) }
func (*ProjectsReply) ProtoMessage()    {}
func (*ProjectsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{6}
}
func (m *ProjectsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectsReply.Unmarshal(m, b)
}
func (m *ProjectsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectsReply.Marshal(b, m, deterministic)
}
func (dst *ProjectsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectsReply.Merge(dst, src)
}
func (m *ProjectsReply) XXX_Size() int {
	return xxx_messageInfo_ProjectsReply.Size(m)
}
func (m *ProjectsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectsReply.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectsReply proto.InternalMessageInfo

func (m *ProjectsReply) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

type UserRole struct {
	Role                 Role     `protobuf:"varint,1,opt,name=role,proto3,enum=types.Role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRole) Reset()         { *m = UserRole{} }
func (m *UserRole) String() string { return proto.CompactTextString(m) }
func (*UserRole) ProtoMessage()    {}
func (*UserRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{7}
}
func (m *UserRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRole.Unmarshal(m, b)
}
func (m *UserRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRole.Marshal(b, m, deterministic)
}
func (dst *UserRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRole.Merge(dst, src)
}
func (m *UserRole) XXX_Size() int {
	return xxx_messageInfo_UserRole.Size(m)
}
func (m *UserRole) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRole.DiscardUnknown(m)
}

var xxx_messageInfo_UserRole proto.InternalMessageInfo

func (m *UserRole) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_GUEST
}

type UpdateUserRequest struct {
	// The user resource which replaces the resource on the server.
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	// The update mask applies to the resource. For the `FieldMask` definition,
	// see https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#fieldmask
	UpdateMask           *types.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{8}
}
func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(dst, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UpdateUserRequest) GetUpdateMask() *types.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type ListProjectsRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProjectsRequest) Reset()         { *m = ListProjectsRequest{} }
func (m *ListProjectsRequest) String() string { return proto.CompactTextString(m) }
func (*ListProjectsRequest) ProtoMessage()    {}
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{9}
}
func (m *ListProjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectsRequest.Unmarshal(m, b)
}
func (m *ListProjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectsRequest.Marshal(b, m, deterministic)
}
func (dst *ListProjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectsRequest.Merge(dst, src)
}
func (m *ListProjectsRequest) XXX_Size() int {
	return xxx_messageInfo_ListProjectsRequest.Size(m)
}
func (m *ListProjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectsRequest proto.InternalMessageInfo

func (m *ListProjectsRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type ListUsersRequest struct {
	// Only list users created after this timestamp
	CreatedSince *time.Time `protobuf:"bytes,1,opt,name=created_since,json=createdSince,stdtime" json:"created_since,omitempty"`
	// Only list users older than this Duration
	OlderThan            *time.Duration `protobuf:"bytes,2,opt,name=older_than,json=olderThan,stdduration" json:"older_than,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{10}
}
func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (dst *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(dst, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

func (m *ListUsersRequest) GetCreatedSince() *time.Time {
	if m != nil {
		return m.CreatedSince
	}
	return nil
}

func (m *ListUsersRequest) GetOlderThan() *time.Duration {
	if m != nil {
		return m.OlderThan
	}
	return nil
}

type CreateDatasetRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Private              bool     `protobuf:"varint,3,opt,name=private,proto3" json:"private,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Preprocessing        string   `protobuf:"bytes,5,opt,name=preprocessing,proto3" json:"preprocessing,omitempty"`
	Format               []string `protobuf:"bytes,6,rep,name=format" json:"format,omitempty"`
	Labels               []string `protobuf:"bytes,7,rep,name=labels" json:"labels,omitempty"`
	Resources            []string `protobuf:"bytes,8,rep,name=resources" json:"resources,omitempty"`
	Lisense              string   `protobuf:"bytes,9,opt,name=lisense,proto3" json:"lisense,omitempty"`
	Reference            []string `protobuf:"bytes,10,rep,name=reference" json:"reference,omitempty"`
	Creators             []string `protobuf:"bytes,11,rep,name=creators" json:"creators,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDatasetRequest) Reset()         { *m = CreateDatasetRequest{} }
func (m *CreateDatasetRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDatasetRequest) ProtoMessage()    {}
func (*CreateDatasetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{11}
}
func (m *CreateDatasetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDatasetRequest.Unmarshal(m, b)
}
func (m *CreateDatasetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDatasetRequest.Marshal(b, m, deterministic)
}
func (dst *CreateDatasetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDatasetRequest.Merge(dst, src)
}
func (m *CreateDatasetRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDatasetRequest.Size(m)
}
func (m *CreateDatasetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDatasetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDatasetRequest proto.InternalMessageInfo

func (m *CreateDatasetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateDatasetRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *CreateDatasetRequest) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

func (m *CreateDatasetRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateDatasetRequest) GetPreprocessing() string {
	if m != nil {
		return m.Preprocessing
	}
	return ""
}

func (m *CreateDatasetRequest) GetFormat() []string {
	if m != nil {
		return m.Format
	}
	return nil
}

func (m *CreateDatasetRequest) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *CreateDatasetRequest) GetResources() []string {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *CreateDatasetRequest) GetLisense() string {
	if m != nil {
		return m.Lisense
	}
	return ""
}

func (m *CreateDatasetRequest) GetReference() []string {
	if m != nil {
		return m.Reference
	}
	return nil
}

func (m *CreateDatasetRequest) GetCreators() []string {
	if m != nil {
		return m.Creators
	}
	return nil
}

type ListDatasetsRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ShowPrivate          bool     `protobuf:"varint,2,opt,name=showPrivate,proto3" json:"showPrivate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDatasetsRequest) Reset()         { *m = ListDatasetsRequest{} }
func (m *ListDatasetsRequest) String() string { return proto.CompactTextString(m) }
func (*ListDatasetsRequest) ProtoMessage()    {}
func (*ListDatasetsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{12}
}
func (m *ListDatasetsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDatasetsRequest.Unmarshal(m, b)
}
func (m *ListDatasetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDatasetsRequest.Marshal(b, m, deterministic)
}
func (dst *ListDatasetsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDatasetsRequest.Merge(dst, src)
}
func (m *ListDatasetsRequest) XXX_Size() int {
	return xxx_messageInfo_ListDatasetsRequest.Size(m)
}
func (m *ListDatasetsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDatasetsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDatasetsRequest proto.InternalMessageInfo

func (m *ListDatasetsRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ListDatasetsRequest) GetShowPrivate() bool {
	if m != nil {
		return m.ShowPrivate
	}
	return false
}

type CreateProjectRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Private              bool     `protobuf:"varint,3,opt,name=private,proto3" json:"private,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	GitRepos             string   `protobuf:"bytes,5,opt,name=git_repos,json=gitRepos,proto3" json:"git_repos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectRequest) Reset()         { *m = CreateProjectRequest{} }
func (m *CreateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProjectRequest) ProtoMessage()    {}
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{13}
}
func (m *CreateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectRequest.Unmarshal(m, b)
}
func (m *CreateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectRequest.Marshal(b, m, deterministic)
}
func (dst *CreateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectRequest.Merge(dst, src)
}
func (m *CreateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProjectRequest.Size(m)
}
func (m *CreateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectRequest proto.InternalMessageInfo

func (m *CreateProjectRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *CreateProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateProjectRequest) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

func (m *CreateProjectRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateProjectRequest) GetGitRepos() string {
	if m != nil {
		return m.GitRepos
	}
	return ""
}

type GetProjectRequest struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProjectRequest) Reset()         { *m = GetProjectRequest{} }
func (m *GetProjectRequest) String() string { return proto.CompactTextString(m) }
func (*GetProjectRequest) ProtoMessage()    {}
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{14}
}
func (m *GetProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectRequest.Unmarshal(m, b)
}
func (m *GetProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectRequest.Marshal(b, m, deterministic)
}
func (dst *GetProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectRequest.Merge(dst, src)
}
func (m *GetProjectRequest) XXX_Size() int {
	return xxx_messageInfo_GetProjectRequest.Size(m)
}
func (m *GetProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectRequest proto.InternalMessageInfo

func (m *GetProjectRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *GetProjectRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteProjectRequest struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Force                bool     `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProjectRequest) Reset()         { *m = DeleteProjectRequest{} }
func (m *DeleteProjectRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteProjectRequest) ProtoMessage()    {}
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{15}
}
func (m *DeleteProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProjectRequest.Unmarshal(m, b)
}
func (m *DeleteProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProjectRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProjectRequest.Merge(dst, src)
}
func (m *DeleteProjectRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteProjectRequest.Size(m)
}
func (m *DeleteProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProjectRequest proto.InternalMessageInfo

func (m *DeleteProjectRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *DeleteProjectRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

type UpdateProjectRequest struct {
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Private:
	//	*UpdateProjectRequest_Value
	Private              isUpdateProjectRequest_Private `protobuf_oneof:"private"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *UpdateProjectRequest) Reset()         { *m = UpdateProjectRequest{} }
func (m *UpdateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProjectRequest) ProtoMessage()    {}
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{16}
}
func (m *UpdateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProjectRequest.Unmarshal(m, b)
}
func (m *UpdateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProjectRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProjectRequest.Merge(dst, src)
}
func (m *UpdateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProjectRequest.Size(m)
}
func (m *UpdateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProjectRequest proto.InternalMessageInfo

type isUpdateProjectRequest_Private interface {
	isUpdateProjectRequest_Private()
}

type UpdateProjectRequest_Value struct {
	Value bool `protobuf:"varint,3,opt,name=value,proto3,oneof"`
}

func (*UpdateProjectRequest_Value) isUpdateProjectRequest_Private() {}

func (m *UpdateProjectRequest) GetPrivate() isUpdateProjectRequest_Private {
	if m != nil {
		return m.Private
	}
	return nil
}

func (m *UpdateProjectRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *UpdateProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateProjectRequest) GetValue() bool {
	if x, ok := m.GetPrivate().(*UpdateProjectRequest_Value); ok {
		return x.Value
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*UpdateProjectRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _UpdateProjectRequest_OneofMarshaler, _UpdateProjectRequest_OneofUnmarshaler, _UpdateProjectRequest_OneofSizer, []interface{}{
		(*UpdateProjectRequest_Value)(nil),
	}
}

func _UpdateProjectRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*UpdateProjectRequest)
	// private
	switch x := m.Private.(type) {
	case *UpdateProjectRequest_Value:
		t := uint64(0)
		if x.Value {
			t = 1
		}
		_ = b.EncodeVarint(3<<3 | proto.WireVarint)
		_ = b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("UpdateProjectRequest.Private has unexpected type %T", x)
	}
	return nil
}

func _UpdateProjectRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*UpdateProjectRequest)
	switch tag {
	case 3: // private.value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Private = &UpdateProjectRequest_Value{x != 0}
		return true, err
	default:
		return false, nil
	}
}

func _UpdateProjectRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*UpdateProjectRequest)
	// private
	switch x := m.Private.(type) {
	case *UpdateProjectRequest_Value:
		n += 1 // tag and wire
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type DatasetsReply struct {
	Datasets             []*Dataset `protobuf:"bytes,1,rep,name=datasets" json:"datasets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DatasetsReply) Reset()         { *m = DatasetsReply{} }
func (m *DatasetsReply) String() string { return proto.CompactTextString(m) }
func (*DatasetsReply) ProtoMessage()    {}
func (*DatasetsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{17}
}
func (m *DatasetsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatasetsReply.Unmarshal(m, b)
}
func (m *DatasetsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatasetsReply.Marshal(b, m, deterministic)
}
func (dst *DatasetsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatasetsReply.Merge(dst, src)
}
func (m *DatasetsReply) XXX_Size() int {
	return xxx_messageInfo_DatasetsReply.Size(m)
}
func (m *DatasetsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DatasetsReply.DiscardUnknown(m)
}

var xxx_messageInfo_DatasetsReply proto.InternalMessageInfo

func (m *DatasetsReply) GetDatasets() []*Dataset {
	if m != nil {
		return m.Datasets
	}
	return nil
}

type DeleteDatasetRequest struct {
	DatasetId            uint32   `protobuf:"varint,1,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDatasetRequest) Reset()         { *m = DeleteDatasetRequest{} }
func (m *DeleteDatasetRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDatasetRequest) ProtoMessage()    {}
func (*DeleteDatasetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{18}
}
func (m *DeleteDatasetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDatasetRequest.Unmarshal(m, b)
}
func (m *DeleteDatasetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDatasetRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteDatasetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDatasetRequest.Merge(dst, src)
}
func (m *DeleteDatasetRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDatasetRequest.Size(m)
}
func (m *DeleteDatasetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDatasetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDatasetRequest proto.InternalMessageInfo

func (m *DeleteDatasetRequest) GetDatasetId() uint32 {
	if m != nil {
		return m.DatasetId
	}
	return 0
}

type RestoreDatasetRequest struct {
	DatasetId            uint32   `protobuf:"varint,1,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreDatasetRequest) Reset()         { *m = RestoreDatasetRequest{} }
func (m *RestoreDatasetRequest) String() string { return proto.CompactTextString(m) }
func (*RestoreDatasetRequest) ProtoMessage()    {}
func (*RestoreDatasetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{19}
}
func (m *RestoreDatasetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreDatasetRequest.Unmarshal(m, b)
}
func (m *RestoreDatasetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreDatasetRequest.Marshal(b, m, deterministic)
}
func (dst *RestoreDatasetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreDatasetRequest.Merge(dst, src)
}
func (m *RestoreDatasetRequest) XXX_Size() int {
	return xxx_messageInfo_RestoreDatasetRequest.Size(m)
}
func (m *RestoreDatasetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreDatasetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreDatasetRequest proto.InternalMessageInfo

func (m *RestoreDatasetRequest) GetDatasetId() uint32 {
	if m != nil {
		return m.DatasetId
	}
	return 0
}

type ListObjectsRequest struct {
	Id                   *ObjectID `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Blob                 string    `protobuf:"bytes,2,opt,name=blob,proto3" json:"blob,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListObjectsRequest) Reset()         { *m = ListObjectsRequest{} }
func (m *ListObjectsRequest) String() string { return proto.CompactTextString(m) }
func (*ListObjectsRequest) ProtoMessage()    {}
func (*ListObjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{20}
}
func (m *ListObjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListObjectsRequest.Unmarshal(m, b)
}
func (m *ListObjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListObjectsRequest.Marshal(b, m, deterministic)
}
func (dst *ListObjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListObjectsRequest.Merge(dst, src)
}
func (m *ListObjectsRequest) XXX_Size() int {
	return xxx_messageInfo_ListObjectsRequest.Size(m)
}
func (m *ListObjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListObjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListObjectsRequest proto.InternalMessageInfo

func (m *ListObjectsRequest) GetId() *ObjectID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ListObjectsRequest) GetBlob() string {
	if m != nil {
		return m.Blob
	}
	return ""
}

type GetObjectRequest struct {
	DatasetId            *ObjectID `protobuf:"bytes,1,opt,name=dataset_id,json=datasetId" json:"dataset_id,omitempty"`
	Blob                 string    `protobuf:"bytes,2,opt,name=blob,proto3" json:"blob,omitempty"`
	PartSize             uint32    `protobuf:"varint,3,opt,name=part_size,json=partSize,proto3" json:"part_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetObjectRequest) Reset()         { *m = GetObjectRequest{} }
func (m *GetObjectRequest) String() string { return proto.CompactTextString(m) }
func (*GetObjectRequest) ProtoMessage()    {}
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{21}
}
func (m *GetObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectRequest.Unmarshal(m, b)
}
func (m *GetObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectRequest.Marshal(b, m, deterministic)
}
func (dst *GetObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectRequest.Merge(dst, src)
}
func (m *GetObjectRequest) XXX_Size() int {
	return xxx_messageInfo_GetObjectRequest.Size(m)
}
func (m *GetObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectRequest proto.InternalMessageInfo

func (m *GetObjectRequest) GetDatasetId() *ObjectID {
	if m != nil {
		return m.DatasetId
	}
	return nil
}

func (m *GetObjectRequest) GetBlob() string {
	if m != nil {
		return m.Blob
	}
	return ""
}

func (m *GetObjectRequest) GetPartSize() uint32 {
	if m != nil {
		return m.PartSize
	}
	return 0
}

type ObjectID struct {
	// Types that are valid to be assigned to Value:
	//	*ObjectID_DatasetId
	//	*ObjectID_Name
	Value                isObjectID_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ObjectID) Reset()         { *m = ObjectID{} }
func (m *ObjectID) String() string { return proto.CompactTextString(m) }
func (*ObjectID) ProtoMessage()    {}
func (*ObjectID) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{22}
}
func (m *ObjectID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectID.Unmarshal(m, b)
}
func (m *ObjectID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectID.Marshal(b, m, deterministic)
}
func (dst *ObjectID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectID.Merge(dst, src)
}
func (m *ObjectID) XXX_Size() int {
	return xxx_messageInfo_ObjectID.Size(m)
}
func (m *ObjectID) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectID.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectID proto.InternalMessageInfo

type isObjectID_Value interface {
	isObjectID_Value()
}

type ObjectID_DatasetId struct {
	DatasetId uint32 `protobuf:"varint,1,opt,name=dataset_id,json=datasetId,proto3,oneof"`
}
type ObjectID_Name struct {
	Name string `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
}

func (*ObjectID_DatasetId) isObjectID_Value() {}
func (*ObjectID_Name) isObjectID_Value()      {}

func (m *ObjectID) GetValue() isObjectID_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ObjectID) GetDatasetId() uint32 {
	if x, ok := m.GetValue().(*ObjectID_DatasetId); ok {
		return x.DatasetId
	}
	return 0
}

func (m *ObjectID) GetName() string {
	if x, ok := m.GetValue().(*ObjectID_Name); ok {
		return x.Name
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ObjectID) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ObjectID_OneofMarshaler, _ObjectID_OneofUnmarshaler, _ObjectID_OneofSizer, []interface{}{
		(*ObjectID_DatasetId)(nil),
		(*ObjectID_Name)(nil),
	}
}

func _ObjectID_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ObjectID)
	// value
	switch x := m.Value.(type) {
	case *ObjectID_DatasetId:
		_ = b.EncodeVarint(1<<3 | proto.WireVarint)
		_ = b.EncodeVarint(uint64(x.DatasetId))
	case *ObjectID_Name:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		_ = b.EncodeStringBytes(x.Name)
	case nil:
	default:
		return fmt.Errorf("ObjectID.Value has unexpected type %T", x)
	}
	return nil
}

func _ObjectID_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ObjectID)
	switch tag {
	case 1: // value.dataset_id
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &ObjectID_DatasetId{uint32(x)}
		return true, err
	case 2: // value.name
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &ObjectID_Name{x}
		return true, err
	default:
		return false, nil
	}
}

func _ObjectID_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ObjectID)
	// value
	switch x := m.Value.(type) {
	case *ObjectID_DatasetId:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.DatasetId))
	case *ObjectID_Name:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Name)))
		n += len(x.Name)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type PutObjectRequest struct {
	// Types that are valid to be assigned to Value:
	//	*PutObjectRequest_Key_
	//	*PutObjectRequest_Chunk_
	Value                isPutObjectRequest_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *PutObjectRequest) Reset()         { *m = PutObjectRequest{} }
func (m *PutObjectRequest) String() string { return proto.CompactTextString(m) }
func (*PutObjectRequest) ProtoMessage()    {}
func (*PutObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{23}
}
func (m *PutObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutObjectRequest.Unmarshal(m, b)
}
func (m *PutObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutObjectRequest.Marshal(b, m, deterministic)
}
func (dst *PutObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutObjectRequest.Merge(dst, src)
}
func (m *PutObjectRequest) XXX_Size() int {
	return xxx_messageInfo_PutObjectRequest.Size(m)
}
func (m *PutObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutObjectRequest proto.InternalMessageInfo

type isPutObjectRequest_Value interface {
	isPutObjectRequest_Value()
}

type PutObjectRequest_Key_ struct {
	Key *PutObjectRequest_Key `protobuf:"bytes,1,opt,name=key,oneof"`
}
type PutObjectRequest_Chunk_ struct {
	Chunk *PutObjectRequest_Chunk `protobuf:"bytes,2,opt,name=chunk,oneof"`
}

func (*PutObjectRequest_Key_) isPutObjectRequest_Value()   {}
func (*PutObjectRequest_Chunk_) isPutObjectRequest_Value() {}

func (m *PutObjectRequest) GetValue() isPutObjectRequest_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *PutObjectRequest) GetKey() *PutObjectRequest_Key {
	if x, ok := m.GetValue().(*PutObjectRequest_Key_); ok {
		return x.Key
	}
	return nil
}

func (m *PutObjectRequest) GetChunk() *PutObjectRequest_Chunk {
	if x, ok := m.GetValue().(*PutObjectRequest_Chunk_); ok {
		return x.Chunk
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PutObjectRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PutObjectRequest_OneofMarshaler, _PutObjectRequest_OneofUnmarshaler, _PutObjectRequest_OneofSizer, []interface{}{
		(*PutObjectRequest_Key_)(nil),
		(*PutObjectRequest_Chunk_)(nil),
	}
}

func _PutObjectRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PutObjectRequest)
	// value
	switch x := m.Value.(type) {
	case *PutObjectRequest_Key_:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Key); err != nil {
			return err
		}
	case *PutObjectRequest_Chunk_:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Chunk); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("PutObjectRequest.Value has unexpected type %T", x)
	}
	return nil
}

func _PutObjectRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PutObjectRequest)
	switch tag {
	case 1: // value.key
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PutObjectRequest_Key)
		err := b.DecodeMessage(msg)
		m.Value = &PutObjectRequest_Key_{msg}
		return true, err
	case 2: // value.chunk
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PutObjectRequest_Chunk)
		err := b.DecodeMessage(msg)
		m.Value = &PutObjectRequest_Chunk_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _PutObjectRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PutObjectRequest)
	// value
	switch x := m.Value.(type) {
	case *PutObjectRequest_Key_:
		s := proto.Size(x.Key)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PutObjectRequest_Chunk_:
		s := proto.Size(x.Chunk)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type PutObjectRequest_Key struct {
	Id                   *ObjectID `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Blob                 string    `protobuf:"bytes,2,opt,name=blob,proto3" json:"blob,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PutObjectRequest_Key) Reset()         { *m = PutObjectRequest_Key{} }
func (m *PutObjectRequest_Key) String() string { return proto.CompactTextString(m) }
func (*PutObjectRequest_Key) ProtoMessage()    {}
func (*PutObjectRequest_Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{23, 0}
}
func (m *PutObjectRequest_Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutObjectRequest_Key.Unmarshal(m, b)
}
func (m *PutObjectRequest_Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutObjectRequest_Key.Marshal(b, m, deterministic)
}
func (dst *PutObjectRequest_Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutObjectRequest_Key.Merge(dst, src)
}
func (m *PutObjectRequest_Key) XXX_Size() int {
	return xxx_messageInfo_PutObjectRequest_Key.Size(m)
}
func (m *PutObjectRequest_Key) XXX_DiscardUnknown() {
	xxx_messageInfo_PutObjectRequest_Key.DiscardUnknown(m)
}

var xxx_messageInfo_PutObjectRequest_Key proto.InternalMessageInfo

func (m *PutObjectRequest_Key) GetId() *ObjectID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *PutObjectRequest_Key) GetBlob() string {
	if m != nil {
		return m.Blob
	}
	return ""
}

type PutObjectRequest_Chunk struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Position             int64    `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutObjectRequest_Chunk) Reset()         { *m = PutObjectRequest_Chunk{} }
func (m *PutObjectRequest_Chunk) String() string { return proto.CompactTextString(m) }
func (*PutObjectRequest_Chunk) ProtoMessage()    {}
func (*PutObjectRequest_Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{23, 1}
}
func (m *PutObjectRequest_Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutObjectRequest_Chunk.Unmarshal(m, b)
}
func (m *PutObjectRequest_Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutObjectRequest_Chunk.Marshal(b, m, deterministic)
}
func (dst *PutObjectRequest_Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutObjectRequest_Chunk.Merge(dst, src)
}
func (m *PutObjectRequest_Chunk) XXX_Size() int {
	return xxx_messageInfo_PutObjectRequest_Chunk.Size(m)
}
func (m *PutObjectRequest_Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_PutObjectRequest_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_PutObjectRequest_Chunk proto.InternalMessageInfo

func (m *PutObjectRequest_Chunk) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *PutObjectRequest_Chunk) GetPosition() int64 {
	if m != nil {
		return m.Position
	}
	return 0
}

type DeleteObjectRequest struct {
	DatasetId            uint32   `protobuf:"varint,1,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	Blob                 string   `protobuf:"bytes,2,opt,name=blob,proto3" json:"blob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteObjectRequest) Reset()         { *m = DeleteObjectRequest{} }
func (m *DeleteObjectRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteObjectRequest) ProtoMessage()    {}
func (*DeleteObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{24}
}
func (m *DeleteObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteObjectRequest.Unmarshal(m, b)
}
func (m *DeleteObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteObjectRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteObjectRequest.Merge(dst, src)
}
func (m *DeleteObjectRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteObjectRequest.Size(m)
}
func (m *DeleteObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteObjectRequest proto.InternalMessageInfo

func (m *DeleteObjectRequest) GetDatasetId() uint32 {
	if m != nil {
		return m.DatasetId
	}
	return 0
}

func (m *DeleteObjectRequest) GetBlob() string {
	if m != nil {
		return m.Blob
	}
	return ""
}

type ObjectReply struct {
	Object               *Object  `protobuf:"bytes,1,opt,name=object" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectReply) Reset()         { *m = ObjectReply{} }
func (m *ObjectReply) String() string { return proto.CompactTextString(m) }
func (*ObjectReply) ProtoMessage()    {}
func (*ObjectReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{25}
}
func (m *ObjectReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectReply.Unmarshal(m, b)
}
func (m *ObjectReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectReply.Marshal(b, m, deterministic)
}
func (dst *ObjectReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectReply.Merge(dst, src)
}
func (m *ObjectReply) XXX_Size() int {
	return xxx_messageInfo_ObjectReply.Size(m)
}
func (m *ObjectReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectReply.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectReply proto.InternalMessageInfo

func (m *ObjectReply) GetObject() *Object {
	if m != nil {
		return m.Object
	}
	return nil
}

type PutObjectReply struct {
	Etag                 string   `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag,omitempty"`
	Size_                uint32   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	VersionId            string   `protobuf:"bytes,3,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutObjectReply) Reset()         { *m = PutObjectReply{} }
func (m *PutObjectReply) String() string { return proto.CompactTextString(m) }
func (*PutObjectReply) ProtoMessage()    {}
func (*PutObjectReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{26}
}
func (m *PutObjectReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutObjectReply.Unmarshal(m, b)
}
func (m *PutObjectReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutObjectReply.Marshal(b, m, deterministic)
}
func (dst *PutObjectReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutObjectReply.Merge(dst, src)
}
func (m *PutObjectReply) XXX_Size() int {
	return xxx_messageInfo_PutObjectReply.Size(m)
}
func (m *PutObjectReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PutObjectReply.DiscardUnknown(m)
}

var xxx_messageInfo_PutObjectReply proto.InternalMessageInfo

func (m *PutObjectReply) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

func (m *PutObjectReply) GetSize_() uint32 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *PutObjectReply) GetVersionId() string {
	if m != nil {
		return m.VersionId
	}
	return ""
}

type GetObjectReply struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Position             int64    `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetObjectReply) Reset()         { *m = GetObjectReply{} }
func (m *GetObjectReply) String() string { return proto.CompactTextString(m) }
func (*GetObjectReply) ProtoMessage()    {}
func (*GetObjectReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{27}
}
func (m *GetObjectReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectReply.Unmarshal(m, b)
}
func (m *GetObjectReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectReply.Marshal(b, m, deterministic)
}
func (dst *GetObjectReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectReply.Merge(dst, src)
}
func (m *GetObjectReply) XXX_Size() int {
	return xxx_messageInfo_GetObjectReply.Size(m)
}
func (m *GetObjectReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectReply proto.InternalMessageInfo

func (m *GetObjectReply) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetObjectReply) GetPosition() int64 {
	if m != nil {
		return m.Position
	}
	return 0
}

type ObjectsReply struct {
	Objects              []*Object `protobuf:"bytes,1,rep,name=objects" json:"objects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ObjectsReply) Reset()         { *m = ObjectsReply{} }
func (m *ObjectsReply) String() string { return proto.CompactTextString(m) }
func (*ObjectsReply) ProtoMessage()    {}
func (*ObjectsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a499a579999dc03b, []int{28}
}
func (m *ObjectsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectsReply.Unmarshal(m, b)
}
func (m *ObjectsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectsReply.Marshal(b, m, deterministic)
}
func (dst *ObjectsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectsReply.Merge(dst, src)
}
func (m *ObjectsReply) XXX_Size() int {
	return xxx_messageInfo_ObjectsReply.Size(m)
}
func (m *ObjectsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectsReply.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectsReply proto.InternalMessageInfo

func (m *ObjectsReply) GetObjects() []*Object {
	if m != nil {
		return m.Objects
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "types.User")
	proto.RegisterType((*Object)(nil), "types.Object")
	proto.RegisterType((*Project)(nil), "types.Project")
	proto.RegisterType((*Dataset)(nil), "types.Dataset")
	proto.RegisterType((*Organization)(nil), "types.Organization")
	proto.RegisterType((*UsersReply)(nil), "types.UsersReply")
	proto.RegisterType((*ProjectsReply)(nil), "types.ProjectsReply")
	proto.RegisterType((*UserRole)(nil), "types.UserRole")
	proto.RegisterType((*UpdateUserRequest)(nil), "types.UpdateUserRequest")
	proto.RegisterType((*ListProjectsRequest)(nil), "types.ListProjectsRequest")
	proto.RegisterType((*ListUsersRequest)(nil), "types.ListUsersRequest")
	proto.RegisterType((*CreateDatasetRequest)(nil), "types.CreateDatasetRequest")
	proto.RegisterType((*ListDatasetsRequest)(nil), "types.ListDatasetsRequest")
	proto.RegisterType((*CreateProjectRequest)(nil), "types.CreateProjectRequest")
	proto.RegisterType((*GetProjectRequest)(nil), "types.GetProjectRequest")
	proto.RegisterType((*DeleteProjectRequest)(nil), "types.DeleteProjectRequest")
	proto.RegisterType((*UpdateProjectRequest)(nil), "types.UpdateProjectRequest")
	proto.RegisterType((*DatasetsReply)(nil), "types.DatasetsReply")
	proto.RegisterType((*DeleteDatasetRequest)(nil), "types.DeleteDatasetRequest")
	proto.RegisterType((*RestoreDatasetRequest)(nil), "types.RestoreDatasetRequest")
	proto.RegisterType((*ListObjectsRequest)(nil), "types.ListObjectsRequest")
	proto.RegisterType((*GetObjectRequest)(nil), "types.GetObjectRequest")
	proto.RegisterType((*ObjectID)(nil), "types.ObjectID")
	proto.RegisterType((*PutObjectRequest)(nil), "types.PutObjectRequest")
	proto.RegisterType((*PutObjectRequest_Key)(nil), "types.PutObjectRequest.Key")
	proto.RegisterType((*PutObjectRequest_Chunk)(nil), "types.PutObjectRequest.Chunk")
	proto.RegisterType((*DeleteObjectRequest)(nil), "types.DeleteObjectRequest")
	proto.RegisterType((*ObjectReply)(nil), "types.ObjectReply")
	proto.RegisterType((*PutObjectReply)(nil), "types.PutObjectReply")
	proto.RegisterType((*GetObjectReply)(nil), "types.GetObjectReply")
	proto.RegisterType((*ObjectsReply)(nil), "types.ObjectsReply")
	proto.RegisterEnum("types.Role", Role_name, Role_value)
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_types_a499a579999dc03b) }

var fileDescriptor_types_a499a579999dc03b = []byte{
	// 1550 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xcb, 0x6f, 0xdb, 0x46,
	0x1a, 0x37, 0xf5, 0xe6, 0x27, 0xcb, 0x51, 0x18, 0x6f, 0xa0, 0x28, 0x71, 0xa4, 0xe5, 0xee, 0x62,
	0x0d, 0xef, 0x5a, 0xc2, 0x7a, 0xf3, 0xc0, 0x6e, 0xd0, 0x87, 0x15, 0xb9, 0xb1, 0x9a, 0xba, 0x09,
	0x98, 0xb8, 0xed, 0xcd, 0x18, 0x89, 0x63, 0x8a, 0x35, 0xc5, 0x61, 0x66, 0x46, 0x36, 0x9c, 0xbf,
	0xa2, 0xc7, 0xf6, 0xd8, 0x53, 0xff, 0x93, 0xa2, 0x87, 0xfe, 0x07, 0x05, 0x12, 0x20, 0xd7, 0xde,
	0x8a, 0x1e, 0x7a, 0x2c, 0xe6, 0x41, 0x89, 0xa2, 0x65, 0xc7, 0x8e, 0x8b, 0x9e, 0x34, 0xdf, 0x93,
	0xdf, 0xf7, 0xfb, 0x1e, 0x33, 0x82, 0x32, 0x3f, 0x8e, 0x30, 0x6b, 0x45, 0x94, 0x70, 0x62, 0xe5,
	0x25, 0x51, 0xbf, 0xe9, 0x11, 0xe2, 0x05, 0xb8, 0x2d, 0x99, 0xfd, 0xf1, 0x7e, 0x1b, 0x8f, 0x22,
	0x7e, 0xac, 0x74, 0xea, 0x8d, 0xb4, 0x90, 0xfb, 0x23, 0xcc, 0x38, 0x1a, 0x45, 0x5a, 0xe1, 0x76,
	0x5a, 0xc1, 0x1d, 0x53, 0xc4, 0x7d, 0x12, 0x6a, 0x79, 0x33, 0x2d, 0xdf, 0xf7, 0x71, 0xe0, 0xee,
	0x8d, 0x10, 0x3b, 0xd0, 0x1a, 0xb7, 0xb4, 0x06, 0x8a, 0xfc, 0x36, 0x0a, 0x43, 0xc2, 0xa5, 0xb9,
	0x0e, 0xb2, 0xfe, 0x6f, 0xf9, 0x33, 0x58, 0xf7, 0x70, 0xb8, 0xce, 0x8e, 0x90, 0xe7, 0x61, 0xda,
	0x26, 0x91, 0xd4, 0x98, 0xa3, 0xbd, 0xee, 0xf9, 0x7c, 0x38, 0xee, 0xb7, 0x06, 0x64, 0xd4, 0xf6,
	0x88, 0x47, 0xa6, 0x9f, 0x15, 0x94, 0x24, 0xe4, 0x49, 0xab, 0xdf, 0x4b, 0xa8, 0x8f, 0x8e, 0x7c,
	0x7e, 0x40, 0x8e, 0xda, 0x1e, 0x59, 0x97, 0xc2, 0xf5, 0x43, 0x14, 0xf8, 0x2e, 0xe2, 0x84, 0xb2,
	0xf6, 0xe4, 0xa8, 0xec, 0xec, 0xef, 0xb2, 0x90, 0xdb, 0x65, 0x98, 0x5a, 0x5d, 0xc8, 0xf8, 0x6e,
	0xcd, 0x68, 0x1a, 0xab, 0x95, 0xce, 0x9d, 0x37, 0xaf, 0x1a, 0x99, 0x5e, 0xf7, 0x97, 0x57, 0x8d,
	0x12, 0x27, 0xd1, 0x67, 0x28, 0x18, 0xe3, 0x37, 0xaf, 0x1b, 0xb7, 0xab, 0x0b, 0x6b, 0xf5, 0x5e,
	0xb7, 0x39, 0x1a, 0x33, 0xde, 0x44, 0xcd, 0x88, 0x30, 0x9f, 0xfb, 0x87, 0xb8, 0xe9, 0x87, 0x1c,
	0x7b, 0x98, 0x3a, 0x19, 0xdf, 0xb5, 0x1a, 0x90, 0xa3, 0x24, 0xc0, 0xb5, 0x4c, 0xd3, 0x58, 0x5d,
	0xda, 0x28, 0xb7, 0x54, 0x91, 0x1c, 0x12, 0x60, 0x47, 0x0a, 0x2c, 0x0b, 0x72, 0x21, 0x1a, 0xe1,
	0x5a, 0xb6, 0x69, 0xac, 0x9a, 0x8e, 0x3c, 0x5b, 0xb7, 0xc0, 0x14, 0xbf, 0x2c, 0x42, 0x03, 0x5c,
	0xcb, 0x49, 0xc1, 0x94, 0x61, 0xad, 0x00, 0xa0, 0x43, 0xc4, 0x11, 0xdd, 0x1b, 0xd3, 0xa0, 0x96,
	0x57, 0x62, 0xc5, 0xd9, 0xa5, 0x81, 0xf5, 0x01, 0xc0, 0x80, 0x62, 0xc4, 0xb1, 0xbb, 0x87, 0x78,
	0xad, 0xd0, 0x34, 0x56, 0xcb, 0x1b, 0xf5, 0x96, 0x2a, 0x44, 0x2b, 0xc6, 0xac, 0xf5, 0x3c, 0xae,
	0x75, 0x27, 0xf7, 0xd5, 0xeb, 0x86, 0xe1, 0x98, 0xda, 0x66, 0x93, 0x0b, 0x07, 0xe3, 0xc8, 0x8d,
	0x1d, 0x14, 0xcf, 0xeb, 0x40, 0xdb, 0x6c, 0x72, 0x6b, 0x0d, 0x4a, 0x11, 0x25, 0x5f, 0xe2, 0x01,
	0x67, 0xb5, 0x52, 0x33, 0xbb, 0x5a, 0xde, 0x58, 0xd2, 0x79, 0x3f, 0x55, 0x6c, 0x67, 0x22, 0xb7,
	0xfe, 0x07, 0x15, 0x42, 0x3d, 0x14, 0xfa, 0x2f, 0x55, 0xb1, 0x6b, 0xa6, 0x34, 0xb8, 0xa6, 0x0d,
	0x9e, 0x24, 0x64, 0xce, 0xac, 0xa6, 0xfd, 0xbd, 0x01, 0x85, 0x27, 0x7d, 0xe1, 0x66, 0x02, 0xa2,
	0x91, 0x00, 0xd1, 0x82, 0x1c, 0xe6, 0xc8, 0x93, 0xc8, 0x9b, 0x8e, 0x3c, 0x0b, 0x1e, 0xf3, 0x5f,
	0x2a, 0xb0, 0x73, 0x8e, 0x3c, 0xa7, 0xf0, 0xca, 0x5d, 0x16, 0xaf, 0xfc, 0x85, 0xf1, 0xb2, 0x7f,
	0x36, 0xa0, 0xa8, 0x91, 0xb1, 0x5a, 0x93, 0xae, 0x33, 0x3b, 0xb7, 0x55, 0xd7, 0xbd, 0x79, 0xdd,
	0x58, 0x5e, 0xab, 0xf6, 0xba, 0xcd, 0x01, 0x0a, 0x79, 0xb3, 0x8f, 0x9b, 0x72, 0x88, 0xbf, 0x30,
	0x64, 0x7f, 0xc5, 0x99, 0x67, 0x4e, 0x6b, 0x9f, 0x6c, 0xba, 0x7d, 0x2e, 0x9d, 0xef, 0xdf, 0xa0,
	0x80, 0xc6, 0x7c, 0x48, 0xa8, 0xce, 0x35, 0x6e, 0x6a, 0x31, 0x35, 0x8e, 0x16, 0x59, 0x35, 0x28,
	0x46, 0xd4, 0x3f, 0x44, 0x1c, 0xcb, 0x16, 0x2c, 0x39, 0x31, 0x69, 0xff, 0x94, 0x83, 0x62, 0x17,
	0x71, 0xc4, 0x30, 0xb7, 0xae, 0x27, 0x66, 0xac, 0xa0, 0xb2, 0x7d, 0xc7, 0xac, 0x9a, 0x50, 0x76,
	0x31, 0x1b, 0x50, 0x5f, 0xee, 0x0f, 0x3d, 0x34, 0x49, 0x96, 0xf5, 0x77, 0xa8, 0x44, 0x14, 0x47,
	0x94, 0x0c, 0x30, 0x63, 0x7e, 0xe8, 0xe9, 0xc9, 0x99, 0x65, 0x8a, 0xaf, 0xf8, 0x21, 0xe3, 0x28,
	0x1c, 0x60, 0x26, 0x23, 0xcf, 0x3b, 0x53, 0x86, 0x75, 0x1d, 0x0a, 0xfb, 0x84, 0x8e, 0xe4, 0x58,
	0x64, 0x57, 0x4d, 0x47, 0x53, 0x82, 0x1f, 0xa0, 0x3e, 0x0e, 0x54, 0xbf, 0x9b, 0x8e, 0xa6, 0x04,
	0xd6, 0xd1, 0xb8, 0x1f, 0xf8, 0x6c, 0x28, 0xb0, 0x36, 0xcf, 0x8b, 0xb5, 0xb6, 0xd9, 0xe4, 0xd6,
	0x7b, 0x60, 0x8e, 0x88, 0xeb, 0xef, 0x1f, 0x0b, 0x7b, 0x38, 0xa7, 0x7d, 0x49, 0x99, 0xa8, 0xd6,
	0x4c, 0xd4, 0xba, 0x7c, 0xf1, 0x5a, 0xdf, 0x02, 0x93, 0x62, 0x46, 0xc6, 0x54, 0xc0, 0xb1, 0x28,
	0x73, 0x9b, 0x32, 0x44, 0x91, 0x03, 0x9f, 0xe1, 0x90, 0xe1, 0x5a, 0x45, 0x82, 0x19, 0x93, 0xca,
	0x6e, 0x1f, 0x53, 0x1c, 0x0e, 0x70, 0x6d, 0x29, 0xb6, 0xd3, 0x0c, 0xab, 0x0e, 0x25, 0xf9, 0x09,
	0x42, 0x59, 0xed, 0x8a, 0x14, 0x4e, 0xe8, 0x64, 0xe3, 0x54, 0x67, 0x1a, 0x27, 0xd1, 0x77, 0x57,
	0x4f, 0xed, 0x3b, 0xfb, 0xd7, 0x0c, 0x2c, 0x26, 0x97, 0xc6, 0x9f, 0xda, 0x62, 0x37, 0xa0, 0xc4,
	0x7c, 0x8e, 0x13, 0x7b, 0xb9, 0x28, 0x68, 0xb1, 0x95, 0x6f, 0x40, 0x69, 0x48, 0x46, 0x4a, 0x54,
	0x50, 0x22, 0x41, 0x0b, 0xd1, 0xec, 0x3e, 0x2f, 0xa6, 0xf7, 0xf9, 0x5f, 0x21, 0x4f, 0x8e, 0x42,
	0x4c, 0x6b, 0xa5, 0x93, 0x59, 0x2b, 0x49, 0xaa, 0xcc, 0xe6, 0x65, 0x57, 0x18, 0x5c, 0x7c, 0x85,
	0xb5, 0x01, 0x44, 0x40, 0xcc, 0xc1, 0x51, 0x70, 0x2c, 0x42, 0x1e, 0x0b, 0xaa, 0x66, 0xc8, 0x65,
	0x3e, 0x1b, 0xb2, 0x94, 0xd8, 0x0f, 0xa0, 0xa2, 0x57, 0x9e, 0xb6, 0x49, 0x5e, 0x1a, 0xc6, 0xd9,
	0x97, 0x86, 0xfd, 0x2f, 0x28, 0x49, 0x5f, 0xe2, 0xfe, 0x8c, 0x2f, 0x58, 0xe3, 0x94, 0x0b, 0xd6,
	0x7e, 0x01, 0x57, 0x77, 0x65, 0x9c, 0xd2, 0x04, 0xbf, 0x18, 0x63, 0xc6, 0x85, 0x95, 0x88, 0x43,
	0x5a, 0xa5, 0x02, 0x94, 0x02, 0xeb, 0x01, 0x94, 0x55, 0x76, 0xf2, 0x39, 0x23, 0xbb, 0x64, 0x1e,
	0x24, 0x1f, 0x89, 0x17, 0xcf, 0x0e, 0x62, 0x07, 0x8e, 0x06, 0x50, 0x9c, 0xed, 0xff, 0xc0, 0xb5,
	0x4f, 0x7c, 0xc6, 0xa7, 0x09, 0xaa, 0x8f, 0xd6, 0xa1, 0x24, 0x7c, 0x27, 0x6e, 0xaa, 0x09, 0x6d,
	0x7f, 0x63, 0x40, 0x55, 0xd8, 0x68, 0x14, 0x95, 0xc1, 0x16, 0x54, 0xe2, 0xba, 0x32, 0x5f, 0x4c,
	0x92, 0x71, 0xce, 0xca, 0x2c, 0x6a, 0xb3, 0x67, 0xc2, 0xca, 0x7a, 0x1f, 0x80, 0x04, 0x2e, 0xa6,
	0x7b, 0x7c, 0x88, 0x42, 0x9d, 0xca, 0x8d, 0x13, 0x3e, 0xba, 0xfa, 0x71, 0xd7, 0xc9, 0x7d, 0x2d,
	0x8b, 0x2b, 0x4d, 0x9e, 0x0f, 0x51, 0x68, 0xff, 0x98, 0x81, 0xe5, 0x87, 0xd2, 0xa1, 0xde, 0xdb,
	0x71, 0x7c, 0xf3, 0xae, 0xdd, 0x99, 0x19, 0xca, 0xa4, 0x67, 0x28, 0x31, 0xdd, 0xd9, 0xd9, 0xe9,
	0xfe, 0xa3, 0x16, 0xf8, 0x74, 0x45, 0x17, 0x4e, 0x59, 0xd1, 0xc5, 0x99, 0x15, 0x3d, 0xb3, 0xe1,
	0x4a, 0x67, 0x6c, 0x38, 0xf3, 0x8c, 0x0d, 0x07, 0x67, 0x6d, 0xb8, 0xf2, 0xec, 0x86, 0xb3, 0x77,
	0x55, 0x77, 0x68, 0x2c, 0x27, 0xc5, 0x9e, 0x01, 0xce, 0x98, 0xb3, 0x7c, 0xd8, 0x90, 0x1c, 0x3d,
	0xd5, 0xe0, 0x65, 0x24, 0x78, 0x49, 0x96, 0xfd, 0xad, 0x11, 0x57, 0x29, 0x1e, 0x98, 0x73, 0x39,
	0x9e, 0xb7, 0x07, 0x2f, 0x53, 0xa5, 0x9b, 0x60, 0x7a, 0x3e, 0xdf, 0xa3, 0x38, 0x22, 0x4c, 0x57,
	0xa8, 0xe4, 0xf9, 0xdc, 0x11, 0xb4, 0xed, 0xc2, 0xd5, 0x47, 0x98, 0xa7, 0xe2, 0x5b, 0x01, 0xd0,
	0x93, 0xbd, 0x17, 0x3f, 0x7d, 0x1c, 0x53, 0x73, 0x7a, 0xee, 0x5b, 0x1a, 0x6a, 0xce, 0xf3, 0xd9,
	0x7e, 0x0c, 0xcb, 0x5d, 0x1c, 0xe0, 0x13, 0x40, 0xbc, 0xe5, 0x43, 0xcb, 0x90, 0xdf, 0x27, 0x74,
	0x10, 0x83, 0xab, 0x08, 0x9b, 0xc2, 0xb2, 0x5a, 0x1f, 0x17, 0x73, 0x56, 0x4b, 0xc2, 0xda, 0xc9,
	0xfd, 0xf0, 0xaa, 0x61, 0x68, 0x70, 0xaf, 0x43, 0xfe, 0x50, 0xfc, 0x81, 0x50, 0xd0, 0x6e, 0x2f,
	0x38, 0x8a, 0xec, 0x98, 0x13, 0xd0, 0xc5, 0x72, 0x9c, 0x76, 0x87, 0x5e, 0x8e, 0xae, 0x66, 0xa4,
	0x96, 0x63, 0x3c, 0x91, 0x13, 0xb9, 0x7d, 0x37, 0xce, 0x3e, 0x35, 0xac, 0x2b, 0x00, 0x5a, 0x27,
	0x0e, 0xb8, 0xe2, 0x98, 0x9a, 0xd3, 0x73, 0xed, 0x7b, 0xf0, 0x17, 0x07, 0x33, 0x4e, 0xe8, 0x05,
	0xed, 0x7a, 0x60, 0x89, 0x6e, 0x56, 0x0f, 0x71, 0x36, 0xdd, 0xaf, 0xf1, 0xad, 0x5b, 0xde, 0xb8,
	0x12, 0xbf, 0xe5, 0xa5, 0xca, 0xf4, 0xfa, 0xed, 0x07, 0xa4, 0x1f, 0xb7, 0x9d, 0x38, 0xdb, 0x0c,
	0xaa, 0x8f, 0xb0, 0xf6, 0x14, 0x3b, 0x6a, 0x9d, 0xf8, 0xfa, 0x1c, 0x87, 0xd3, 0x70, 0xe6, 0xf9,
	0x15, 0x2d, 0x19, 0x21, 0xca, 0xf7, 0x26, 0x4f, 0xff, 0x8a, 0x53, 0x12, 0x8c, 0x67, 0xfe, 0x4b,
	0x6c, 0x7f, 0x0c, 0xa5, 0xd8, 0x8f, 0xd5, 0x38, 0x99, 0xea, 0xf6, 0x42, 0xd2, 0xfb, 0x72, 0xb2,
	0xaa, 0xdb, 0x0b, 0xaa, 0xa2, 0x9d, 0xa2, 0xae, 0xa8, 0xfd, 0x9b, 0x01, 0xd5, 0xa7, 0xe3, 0x54,
	0x06, 0x6d, 0xc8, 0x1e, 0xe0, 0x63, 0x1d, 0xfa, 0xcd, 0xf8, 0x4e, 0x4b, 0x69, 0xb5, 0x1e, 0xe3,
	0xe3, 0xed, 0x05, 0x47, 0x68, 0x5a, 0x77, 0x21, 0x3f, 0x18, 0x8e, 0xc3, 0xf8, 0xd2, 0x59, 0x39,
	0xcd, 0xe4, 0xa1, 0x50, 0x12, 0xfd, 0x23, 0xb5, 0xeb, 0xff, 0x87, 0xec, 0x63, 0x7c, 0xfc, 0x4e,
	0xc8, 0xd7, 0xef, 0x43, 0x5e, 0x7a, 0x13, 0x42, 0x91, 0xad, 0xb4, 0x5f, 0x74, 0xe4, 0x59, 0xec,
	0x32, 0xf5, 0xd7, 0x96, 0xa8, 0xcb, 0x23, 0xeb, 0x4c, 0xe8, 0x69, 0xea, 0xdb, 0x70, 0x4d, 0x75,
	0xdd, 0x6c, 0xf2, 0x67, 0x37, 0xcf, 0xdc, 0x2e, 0xb8, 0x03, 0xe5, 0xd8, 0x87, 0x68, 0xfd, 0x7f,
	0x40, 0x81, 0x48, 0x52, 0xe7, 0x54, 0x99, 0xc9, 0xc9, 0xd1, 0x42, 0xfb, 0x73, 0x58, 0x4a, 0x00,
	0x24, 0x0c, 0xe3, 0xff, 0x7f, 0xc6, 0x9c, 0xff, 0x7f, 0x19, 0x19, 0x88, 0xfa, 0xff, 0xb7, 0x02,
	0x70, 0x88, 0x29, 0xf3, 0x49, 0x28, 0x42, 0xd4, 0xaf, 0x3e, 0xcd, 0xe9, 0xb9, 0xf6, 0x87, 0xb0,
	0x94, 0x68, 0x4a, 0xed, 0xf8, 0x22, 0x18, 0xd9, 0xf7, 0x61, 0x71, 0x32, 0x1d, 0xc2, 0xfe, 0x9f,
	0x50, 0x54, 0x41, 0xc7, 0xb3, 0x9c, 0x4a, 0x29, 0x96, 0xae, 0xad, 0x42, 0x4e, 0x3e, 0x71, 0x4c,
	0xc8, 0x3f, 0xda, 0xdd, 0x7a, 0xf6, 0xbc, 0xba, 0x60, 0x01, 0x14, 0x76, 0xb6, 0x76, 0x3a, 0x5b,
	0x4e, 0xd5, 0x10, 0xec, 0xcd, 0xee, 0x4e, 0xef, 0xd3, 0x6a, 0xa6, 0x5f, 0x90, 0xb7, 0xf8, 0x7f,
	0x7f, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x00, 0x44, 0x29, 0xfd, 0x04, 0x12, 0x00, 0x00,
}
