// Code generated by "stringer -type=DataSource"; DO NOT EDIT.

package predata

import "strconv"

const _DataSource_name = "HubDataUserDataPrivateDataWideDataLocalDataInvalidData"

var _DataSource_index = [...]uint8{0, 7, 15, 26, 34, 43, 54}

func (i DataSource) String() string {
	if i < 0 || i >= DataSource(len(_DataSource_index)-1) {
		return "DataSource(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataSource_name[_DataSource_index[i]:_DataSource_index[i+1]]
}
