// Code generated by "stringer -type GRoleType"; DO NOT EDIT.

package acl

import "strconv"

const _GRoleType_name = "AuthorsContributors"

var _GRoleType_index = [...]uint8{0, 7, 19}

func (i GRoleType) String() string {
	if i < 0 || i >= GRoleType(len(_GRoleType_index)-1) {
		return "GRoleType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GRoleType_name[_GRoleType_index[i]:_GRoleType_index[i+1]]
}
