// Code generated by "stringer -type RoleType"; DO NOT EDIT.

package acl

import "strconv"

const _RoleType_name = "UserOrganizationStaffAdmin"

var _RoleType_index = [...]uint8{0, 4, 16, 21, 26}

func (i RoleType) String() string {
	if i < 0 || i >= RoleType(len(_RoleType_index)-1) {
		return "RoleType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RoleType_name[_RoleType_index[i]:_RoleType_index[i+1]]
}
